###Obtener todos los propietarios
GET http://localhost:3000/api/propietarios

###Agregar un propietarios
# @name createPropietario
POST http://localhost:3000/api/propietarios
Content-Type: application/json

{
  "nombrePropietario": "Irina",
  "apellidoPropietario": "Repupilli",
  "mailPropietario": "irirepupill@gmail.com",
  "telefonoPropietario": "3364574777"
}

###
# @name createPropietario2
POST http://localhost:3000/api/propietarios
Content-Type: application/json

{
  "nombrePropietario": "Cesar",
  "apellidoPropietario": "Repupilli",
  "mailPropietario": "cibercesar6@gmail.com",
  "telefonoPropietario": "12345678"
}

###Obtener un propietario
GET http://localhost:3000/api/propietarios/1


###Modificar un propietario, completo
PUT http://localhost:3000/api/propietarios/1
Content-Type: application/json

{
  "nombrePropietario": "Viviana",
  "apellidoPropietario": "Ziros",
  "mailPropietario": "viviziros@gmail.com",
  "telefonoPropietario": "3364574777"
}

###Modi parcial
PATCH http://localhost:3000/api/propietarios/2
Content-Type: application/json

{
  "nombrePropietario": "Bianca",
  "apellidoPropietario": "Repupilli",
  "telefonoPropietario": "5564574777"
}


###Borrar un propietario
DELETE http://localhost:3000/api/propietarios/9

