###Find all
GET http://localhost:3000/api/tipoServicios

###Add
# @name createTipoServicio
POST http://localhost:3000/api/tipoServicios
Content-Type: application/json

{
  "nombreTipoServicio": "Compra",
  "descripcionTipoServicio": "Inmuebles en venta"
}

###
# @name createTipoServicio2
POST http://localhost:3000/api/tipoServicios
Content-Type: application/json

{
  "nombreTipoServicio": "Alquiler short",
  "descripcionTipoServicio": "Alquiler de inmuebles a corto plazo"
}

###Get one
GET http://localhost:3000/api/tipoServicios/1

###Update complete
PUT http://localhost:3000/api/tipoServicios/2
Content-Type: application/json

{
  "nombreTipoServicio": "Alquiler Long",
  "descripcionTipoServicio": "Alquiler de inmuebles a largo plazo"
}

###Delete
DELETE http://localhost:3000/api/tipoServicios/1