###Find all
GET http://localhost:3000/api/usuarios

###Add
# @name createUsuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Cesar",
  "apellido": "Repupilli",
  "email": "cibercesar6@hotmail.com",
  "password": "12345678",
  "telefono": "3364574777",
  "rol": "ADMIN"
}

###
# @name createUsuario2
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Viviana",
  "apellido": "Ziros",
  "email": "viviziros@hotmail.com",
  "password": "12345655",
  "telefono": "3364574777",
  "rol": "USER"
}

###Find one
GET http://localhost:3000/api/usuarios/1

###Update complete
PUT http://localhost:3000/api/usuarios/1
Content-Type: application/json

{
  "nombre": "Anibal",
  "apellido": "Nuñez",
  "email": "anibalNunez@gmail.com",
  "password": "1234564444",
  "telefono": "3364574777",
  "rol": "ADMIN"
}


###Delete
DELETE http://localhost:3000/api/usuarios/1