###Find all
GET http://localhost:3000/api/localidades


### POST
# @name crearLocalidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "codPostal": "3000",
    "nombre": "Santa Fe"
}

###
# @name crearLocalidad2
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "codPostal": "2000",
    "nombre": "Rosario"
}


### GET ONE
# @name obtenerLocalidad
GET http://localhost:3000/api/localidades/1


### PUT
# @name modificarLocalidad
PUT http://localhost:3000/api/localidades/1
Content-Type: application/json

{
    "codPostal": "2200",
    "nombre": "San Lorenzo"
}
###
# @name modificarLocalidad2
PUT http://localhost:3000/api/localidades/2
Content-Type: application/json

{
    "codPostal": "2001",
    "nombre": "Rosario Norte"
}


### DELETE
# @name borrarLocalidad
DELETE http://localhost:3000/api/localidades/1
