###Find all
GET http://localhost:3000/api/localidades

### POST
# @name crearLocalidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "codPostal": 3000,
    "nombre": "Santa Fe"
}

###ID
@id = {{crearLocalidad.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/localidades/{{id}}

### PUT
# PUT http://localhost:3000/api/localidades/{{id}}
# Content-Type: application/json

# {
#     "codPostal": 2001,
#     "nombre": "Rosario Norte"
# }
### POST 2
# @name crearLocalidadToDelete
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "codPostal": 2200,
    "nombre": "San Lorenzo"
}

###Id to delete
@idToDelete = {{crearLocalidadToDelete.response.body.data.id}}

### DELETE
DELETE http://localhost:3000/api/localidades/{{idToDelete}}