### GET ALL
GET http://localhost:3000/api/consultas

### POST
# @name createConsulta
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dateconsulta": "2025-03-12",
    "descriptionconsulta": "El agente inmobiliaro juan mostró el dpto, y se quejó de que el anterior agente inmobiliario no habia limpiado el dpto en su ultima visita",
    "inmueble": 3,    
    "usuario": 1 
}

### ID
@id = {{createConsulta.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/consultas/{{id}}


### PUT
PUT  http://localhost:3000/api/consultas/{{id}}
Content-Type: application/json

{
    "dateconsulta": "2025-04-10",
    "descriptionconsulta": "El agente inmobiliario Lorenzo comenta que los clientes que querian aluquilar eran adolescentes problematicos, no recomendados",
    "inmueble": 3,    
    "usuario": 2 
}

### POST2
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dateconsulta": "2025-07-10",
    "inmueble": 3,    
    "usuario": 2 
}

### POST3
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dateconsulta": "2025-06-24",
    "inmueble": 3,    
    "usuario": 1 
}

### POST CHARACTER TO DELETE
# @name createConsultaToDelete
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "dateconsulta": "2025-07-14",
    "inmueble": 3,    
    "usuario": 1 
}

### DELETE
@idToDelete = {{createConsultaToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/consultas/{{idToDelete}}